import { computeVerification } from "@/lib/verification";
import { redactEnv, redactText, summarize } from "@/lib/redaction";

import type { TraceDetail } from "@/lib/db/queries/traces";

export interface BuildMarkdownOptions {
  redact: boolean;
  redactLocalPaths?: boolean;
}

function fmt(value: number | null | undefined, digits = 1, unit = ""): string {
  if (value === null || value === undefined) return "—";
  return `${value.toFixed(digits)}${unit}`;
}

function fmtInt(v: number | null | undefined, unit = ""): string {
  if (v === null || v === undefined) return "—";
  return `${v.toLocaleString()}${unit}`;
}

type MP = TraceDetail["metricPoints"][number];

function aggMax(
  points: TraceDetail["metricPoints"],
  getter: (p: MP) => number | null | undefined,
): number | null {
  const v = points
    .map(getter)
    .filter((x): x is number => typeof x === "number");
  return v.length ? Math.max(...v) : null;
}

function aggMin(
  points: TraceDetail["metricPoints"],
  getter: (p: MP) => number | null | undefined,
): number | null {
  const v = points
    .map(getter)
    .filter((x): x is number => typeof x === "number");
  return v.length ? Math.min(...v) : null;
}

export function buildMarkdown(
  trace: TraceDetail,
  options: BuildMarkdownOptions,
): { markdown: string; redactionTotals: { label: string; count: number }[] } {
  const verification = computeVerification(trace);
  const points = trace.metricPoints;
  const counts: Record<string, number> = {};
  const merge = (c: Record<string, number>) => {
    for (const [k, v] of Object.entries(c)) counts[k] = (counts[k] ?? 0) + v;
  };

  let launchCommand = trace.loaderConfig?.launchCommand ?? "";
  let benchmarkCommand = trace.benchmarkProfile?.command ?? "";
  let envVars = trace.loaderConfig?.environmentVariables ?? {};

  if (options.redact) {
    if (launchCommand) {
      const r = redactText(launchCommand, {
        redactLocalPaths: options.redactLocalPaths,
      });
      launchCommand = r.text;
      merge(r.counts);
    }
    if (benchmarkCommand) {
      const r = redactText(benchmarkCommand, {
        redactLocalPaths: options.redactLocalPaths,
      });
      benchmarkCommand = r.text;
      merge(r.counts);
    }
    const r = redactEnv(envVars, {
      redactLocalPaths: options.redactLocalPaths,
    });
    envVars = r.env;
    merge(r.counts);
  }

  const gpus = trace.hardwareProfile.gpuModels ?? [];
  const gpuSummary =
    gpus.length > 0
      ? `${trace.hardwareProfile.gpuCount ?? gpus.length}× ${gpus[0]?.name ?? ""}`
      : "—";

  const lines: string[] = [];
  lines.push(`# ${trace.name}`);
  lines.push("");
  lines.push(`> _Generated by BenchTrace · benchtrace.share.v1_`);
  if (trace.notes) {
    lines.push("");
    lines.push(`${trace.notes}`);
  }
  lines.push("");

  // Summary block
  lines.push("## Summary");
  lines.push("");
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **Model** | ${trace.model.name} ${trace.model.quantization ? `(${trace.model.quantization})` : ""} |`);
  lines.push(`| **Engine** | ${trace.engine.name} ${trace.engine.version ?? ""} |`);
  lines.push(`| **Hardware** | ${gpuSummary} · ${trace.hardwareProfile.cpu ?? "—"} |`);
  lines.push(`| **Context length** | ${fmtInt(trace.contextLength)} |`);
  if (trace.benchmarkProfile) {
    lines.push(
      `| **Workload** | ${trace.benchmarkProfile.workloadType ?? "—"} · input ${fmtInt(trace.benchmarkProfile.inputLength)} · output ${fmtInt(trace.benchmarkProfile.outputLength)} · concurrency ${fmtInt(trace.benchmarkProfile.concurrency)} |`,
    );
  }
  lines.push(`| **Verification** | ${verification.level} |`);
  lines.push("");

  // Results
  lines.push("## Results");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|---|--:|`);
  lines.push(
    `| Best output tok/s | ${fmt(aggMax(points, (p) => p.outputTokensPerSecond))} |`,
  );
  lines.push(
    `| Total tok/s | ${fmt(aggMax(points, (p) => p.totalTokensPerSecond))} |`,
  );
  lines.push(
    `| Prefill tok/s | ${fmt(aggMax(points, (p) => p.prefillTokensPerSecond))} |`,
  );
  lines.push(
    `| Max concurrency | ${fmtInt(aggMax(points, (p) => p.concurrency))} |`,
  );
  lines.push(`| TTFT p50 | ${fmt(aggMin(points, (p) => p.p50TtftMs), 0, " ms")} |`);
  lines.push(`| TTFT p95 | ${fmt(aggMin(points, (p) => p.p95TtftMs), 0, " ms")} |`);
  lines.push(`| TPOT p95 | ${fmt(aggMin(points, (p) => p.p95TpotMs), 1, " ms")} |`);
  lines.push(`| Peak VRAM | ${fmt(aggMax(points, (p) => p.peakVramGb), 1, " GB")} |`);
  if (aggMax(points, (p) => p.powerDrawWattsAvg) != null) {
    lines.push(
      `| Avg power | ${fmt(aggMax(points, (p) => p.powerDrawWattsAvg), 0, " W")} |`,
    );
    lines.push(
      `| Tokens / Watt | ${fmt(aggMax(points, (p) => p.tokensPerWatt), 2)} |`,
    );
  }
  lines.push("");

  // Hardware
  lines.push("## Hardware");
  lines.push("");
  lines.push(`- **CPU**: ${trace.hardwareProfile.cpu ?? "—"}`);
  lines.push(`- **RAM**: ${fmtInt(trace.hardwareProfile.ramGb, " GB")}`);
  lines.push(`- **OS**: ${trace.hardwareProfile.os ?? "—"} (${trace.hardwareProfile.kernel ?? "—"})`);
  lines.push(`- **Driver**: ${trace.hardwareProfile.driverVersion ?? "—"}`);
  lines.push(`- **CUDA/ROCm**: ${trace.hardwareProfile.cudaVersion ?? trace.hardwareProfile.rocmVersion ?? "—"}`);
  for (const g of gpus) {
    lines.push(
      `- **GPU**: ${g.name}${g.vramGb != null ? ` · ${g.vramGb} GB` : ""}${g.pcieGeneration ? ` · ${g.pcieGeneration} ${g.pcieWidth ?? ""}` : ""}`,
    );
  }
  lines.push("");

  // Loader
  lines.push("## Loader / Runtime");
  lines.push("");
  const lc = trace.loaderConfig;
  if (lc) {
    lines.push(
      `- **TP / PP / DP**: ${lc.tensorParallelSize ?? "—"} / ${lc.pipelineParallelSize ?? "—"} / ${lc.dataParallelSize ?? "—"}`,
    );
    lines.push(`- **KV cache dtype**: ${lc.kvCacheDtype ?? "—"}`);
    lines.push(`- **max_model_len**: ${fmtInt(lc.maxModelLen)}`);
    if (lc.flashAttention != null)
      lines.push(`- **Flash attention**: ${lc.flashAttention ? "on" : "off"}`);
    if (lc.speculativeDecoding)
      lines.push(`- **Speculative decoding**: on${lc.draftModel ? ` (draft: ${lc.draftModel})` : ""}`);
    if (lc.mtpEnabled) lines.push(`- **MTP**: enabled`);
    if (lc.chunkedPrefill != null)
      lines.push(`- **Chunked prefill**: ${lc.chunkedPrefill ? "on" : "off"}`);
    if (lc.prefixCaching != null)
      lines.push(`- **Prefix caching**: ${lc.prefixCaching ? "on" : "off"}`);
  } else {
    lines.push("_No loader configuration captured._");
  }
  lines.push("");

  // Commands
  lines.push("## Commands");
  lines.push("");
  lines.push("<details><summary>Launch command</summary>");
  lines.push("");
  lines.push("```bash");
  lines.push(launchCommand || "# not captured");
  lines.push("```");
  lines.push("</details>");
  lines.push("");
  lines.push("<details><summary>Benchmark command</summary>");
  lines.push("");
  lines.push("```bash");
  lines.push(benchmarkCommand || "# not captured");
  lines.push("```");
  lines.push("</details>");
  if (Object.keys(envVars).length > 0) {
    lines.push("");
    lines.push("<details><summary>Environment</summary>");
    lines.push("");
    lines.push("```");
    for (const [k, v] of Object.entries(envVars)) lines.push(`${k}=${v}`);
    lines.push("```");
    lines.push("</details>");
  }
  lines.push("");

  // Verification + missing fields
  lines.push("## Verification");
  lines.push("");
  lines.push(`Level: **${verification.level}**`);
  if (verification.warnings.length) {
    lines.push("");
    lines.push("⚠️ Warnings:");
    for (const w of verification.warnings) lines.push(`- ${w}`);
  }
  if (verification.missingCriticalFields.length) {
    lines.push("");
    lines.push("Missing critical fields:");
    for (const f of verification.missingCriticalFields)
      lines.push(`- \`${f}\``);
  }
  lines.push("");
  lines.push("_Generated by [BenchTrace](https://github.com/) · `benchtrace.share.v1`_");

  return { markdown: lines.join("\n"), redactionTotals: summarize(counts).counts };
}
