import type { LevelAggregate, SweepResult } from "../runner/aggregate";
import type { BenchServeOptions } from "../runner/sweep";
import type { HardwareSnapshot } from "../snapshot/hardware";
import { metricFamilyView, type MetricMode } from "@/lib/metric-family";

export interface MarkdownInput {
  options: BenchServeOptions;
  startedAt: Date;
  completedAt: Date;
  sweep: SweepResult;
  hardware: HardwareSnapshot | null;
  launchCommandPresent: boolean;
  verificationLevel: string;
  redactedBenchmarkCommand: string;
  redactedLaunchCommand: string | null;
}

function fmt(value: number | null | undefined, digits = 1, unit = ""): string {
  if (value == null) return "—";
  return `${value.toFixed(digits)}${unit}`;
}

function fmtInt(v: number | null | undefined, unit = ""): string {
  if (v == null) return "—";
  return `${v.toLocaleString()}${unit}`;
}

export function buildMarkdownSummary(input: MarkdownInput): string {
  const { options, sweep, hardware, verificationLevel } = input;
  const fam = metricFamilyView(options.metricMode as MetricMode);
  const latColLabel = fam.primaryIsChunkGap ? "Chunk-gap p95 (ms)" : "TPOT p95 (ms)";
  const latColValue = (l: LevelAggregate): number | null =>
    fam.primaryIsChunkGap ? l.p95ChunkGapMs : l.p95TpotMs;
  const lines: string[] = [];
  const titleEngine = `${options.engineName}${options.engineVersion !== "unknown" ? ` ${options.engineVersion}` : ""}`;
  lines.push(
    `# BenchTrace · BT-SERVE-001 · ${options.model} · ${titleEngine}`,
  );
  lines.push("");
  lines.push(`> _Generated by BenchTrace native benchmark · benchtrace.share.v1_`);
  if (options.notes) {
    lines.push("");
    lines.push(`${options.notes}`);
  }
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **Profile** | BT-SERVE-001 (Serving Concurrency) |`);
  lines.push(`| **Engine** | ${titleEngine} |`);
  lines.push(`| **Endpoint** | \`${options.baseUrl}${options.endpoint}\` |`);
  lines.push(`| **Streams swept** | ${options.streams.join(", ")} |`);
  lines.push(
    `| **Workload** | input ${options.inputLen} · output ${options.outputLen} · ${options.numPrompts} prompts/level · streaming=${options.streaming} |`,
  );
  lines.push(
    `| **SLAs** | TTFT p95 ≤ ${options.ttftSlaMs} ms · ${fam.primaryLabel} ≤ ${options.tpotSlaMs} ms · failure ≤ ${(options.failureThreshold * 100).toFixed(0)}% |`,
  );
  lines.push(
    `| **Max valid concurrency** | ${sweep.maxValidConcurrency ?? "**none** — all levels exceeded SLAs"} |`,
  );
  lines.push(
    `| **Best output tok/s** | ${fmt(sweep.bestOutputTokensPerSecond)} |`,
  );
  lines.push(`| **Verification** | ${verificationLevel} |`);
  lines.push("");

  lines.push("## Per-stream-level results");
  lines.push("");
  if (fam.note) {
    lines.push(`> ⚠ ${fam.note}`);
    lines.push("");
  }
  if (fam.showBoth) {
    lines.push(
      `| Streams | OK / Total | Output tok/s | TTFT p95 (ms) | TPOT p95 (ms) | Chunk-gap p95 (ms) | E2E p95 (ms) | Failure rate | Status |`,
    );
    lines.push(`|--:|---|--:|--:|--:|--:|--:|--:|---|`);
    for (const l of sweep.perLevel) {
      lines.push(
        `| ${l.streamLevel} | ${l.successfulRequests}/${l.requestCount} | ${fmt(l.outputTokensPerSecond)} | ${fmt(l.p95TtftMs, 0)} | ${fmt(l.p95TpotMs)} | ${fmt(l.p95ChunkGapMs)} | ${fmt(l.p95E2eLatencyMs, 0)} | ${(l.failureRate * 100).toFixed(1)}% | ${l.isValid ? "✅ valid" : "❌ " + summarizeInvalid(l)} |`,
      );
    }
  } else {
    lines.push(
      `| Streams | OK / Total | Output tok/s | TTFT p95 (ms) | ${latColLabel} | E2E p95 (ms) | Failure rate | Status |`,
    );
    lines.push(`|--:|---|--:|--:|--:|--:|--:|---|`);
    for (const l of sweep.perLevel) {
      lines.push(
        `| ${l.streamLevel} | ${l.successfulRequests}/${l.requestCount} | ${fmt(l.outputTokensPerSecond)} | ${fmt(l.p95TtftMs, 0)} | ${fmt(latColValue(l))} | ${fmt(l.p95E2eLatencyMs, 0)} | ${(l.failureRate * 100).toFixed(1)}% | ${l.isValid ? "✅ valid" : "❌ " + summarizeInvalid(l)} |`,
      );
    }
  }
  lines.push("");

  if (sweep.invalidLevels.length > 0) {
    lines.push("### Invalid stream levels");
    lines.push("");
    for (const inv of sweep.invalidLevels) {
      lines.push(`- **${inv.streamLevel} streams**: ${inv.reasons.join("; ")}`);
    }
    lines.push("");
  }

  lines.push("## Hardware");
  lines.push("");
  if (hardware) {
    lines.push(`- **OS**: ${hardware.os ?? "not_captured"} (${hardware.kernel ?? "not_captured"})`);
    lines.push(`- **CPU**: ${hardware.cpu ?? "not_captured"}`);
    lines.push(`- **RAM**: ${fmtInt(hardware.ramGb, " GB")}`);
    lines.push(`- **Driver**: ${hardware.driverVersion ?? "not_captured"}`);
    lines.push(`- **CUDA**: ${hardware.cudaVersion ?? "not_captured"}`);
    if (hardware.gpuModels.length === 0) {
      lines.push(`- **GPUs**: not_captured`);
    } else {
      for (const g of hardware.gpuModels) {
        lines.push(`- **GPU**: ${g.name}${g.vramGb != null ? ` · ${g.vramGb} GB` : ""}`);
      }
    }
    lines.push(`- **Container**: ${hardware.containerRuntime ?? "not_captured"}`);
  } else {
    lines.push("_Hardware snapshot unavailable._");
  }
  lines.push("");

  lines.push("## Commands");
  lines.push("");
  lines.push("<details><summary>Benchmark command</summary>");
  lines.push("");
  lines.push("```bash");
  lines.push(input.redactedBenchmarkCommand);
  lines.push("```");
  lines.push("</details>");
  lines.push("");
  lines.push("<details><summary>Launch command</summary>");
  lines.push("");
  lines.push("```bash");
  lines.push(
    input.redactedLaunchCommand && input.redactedLaunchCommand.length > 0
      ? input.redactedLaunchCommand
      : "# launch_command_not_provided\n# Pass --launch-command-file to record how the server was started.",
  );
  lines.push("```");
  lines.push("</details>");
  lines.push("");

  if (sweep.warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");
    for (const w of sweep.warnings) lines.push(`- ⚠ ${w}`);
    lines.push("");
  }

  lines.push("_Generated by BenchTrace · `benchtrace.share.v1`_");
  return lines.join("\n");
}

function summarizeInvalid(l: LevelAggregate): string {
  if (l.invalidReasons.length === 0) return "invalid";
  if (l.invalidReasons.length === 1) return l.invalidReasons[0]!;
  return `${l.invalidReasons[0]!} (+${l.invalidReasons.length - 1})`;
}
